export default {
    SET_SELECTED_AUTHOR: "SET_SELECTED_AUTHOR",
    ADD_AUTHOR: "ADD_AUTHOR",
    ADD_MOVIE: "ADD_MOVIE",
    REMOVE_AUTHOR: "REMOVE_AUTHOR",
    REMOVE_MOVIE: "REMOVE_MOVIE",
    SET_AS_FAVORITE_AUTHOR: "SET_AS_FAVORITE_AUTHOR",
    SET_AS_FAVORITE_MOVIE: "SET_AS_FAVORITE_MOVIE"
}